version: '3.5'

services:
  mongo-db:
    image: mongo
    container_name: sp-etv-mongodb
    ports:
      - "27017-27019:27017-27019"
    networks:
      - sp-network
  node-api:
    container_name: sp-etv-app
    restart: always
    ports:
      - "3000:3000"
    image: sp-etv-node-js
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    command: "npm start"
    networks:
      - sp-network
networks:
  sp-network:
    name: sp-network
    driver: bridge
